server:
  port: 8081

spring:
  application:
    name: "elmServer"
##    配置security登录用户和密码
  security:
    user:
      name: admin
      password: 123456
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  datasource:
    url: "jdbc:sqlserver://127.0.0.1:11069;DatabaseName=Software_Practical_Training;TrustServerCertificate=true"
    username: "sa"
    password: "180714"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
##    数据库表修改，自动生成、如已经有数据库表，尽量关闭
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#       globally_quoted_identifiers: true
#      naming:
##      jpa命名策略
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#logging:
#  level:

#配置日志
logging:
  level:
    com.example: debug
    root: info
  config: classpath:logging-config.xml
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs
sqlserver:
  jdbc:
    dburl: "jdbc:sqlserver://127.0.0.1:11069;DatabaseName=Software_Practical_Training;TrustServerCertificate=true;user=sa;password=180714;"
