server:
  port: 8081

spring:
  application:
    name: "elmServer"
  datasource:
    url: "jdbc:sqlserver://127.0.0.1:11069;DatabaseName=Software_Practical_Training;TrustServerCertificate=true"
    username: "sa"
    password: "180714"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

#business:
#  security:
#    userName: "admin"
#    password: "123456"

sqlserver:
  jdbc:
    dburl: "jdbc:sqlserver://127.0.0.1:11069;DatabaseName=Software_Practical_Training;TrustServerCertificate=true;user=sa;password=180714;"
